set -g default-terminal "xterm-256color"    # Set this to allow vim to have color schemes
set -g prefix C-a                           # Change special combo to ctrl + a
bind \\ split-window -h                      # Split panes horizontal
bind - split-window -v                      # Split panes vertically
